apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }} #events-service
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
    spec:
      containers:
        - name: {{ .Values.app }}          
          image: {{ .Values.image.repository }} #:{{ .Values.image.tag | default .Chart.AppVersion }}
          # envFrom:
          # - configMapRef:
          #     name: zerotask-asp-net-services-config
          # - configMapRef:
          #     name: zerotask-events-config          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
  ports:
{{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: {{ .protocol }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
{{- end }}